# Generated by Django 5.2.10 on 2026-02-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="review",
            name="restaurant",
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
    ]
