# Generated by Django 5.2.10 on 2026-06-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.booking'),
        ),
    ]
