# Generated by Django 5.2.10 on 2026-02-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserve", "0004_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
