# Generated by Django 5.2.10 on 2026-06-30 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_package_image_alter_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('camera', 'Camera'), ('camping', 'Camping'), ('clothing', 'Clothing'), ('hiking', 'Hiking'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='package',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='reserve.booking'),
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='reserve.booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.equipment'),
        ),
        migrations.AddField(
            model_name='package',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.vehicle'),
        ),
    ]
