# Generated by Django 5.2.10 on 2026-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_equipment_vehicle_rename_price_package_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
