# Generated by Django 5.2.10 on 2026-06-30 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_remove_vehicle_price_per_day_vehicle_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
