# Generated by Django 5.2.10 on 2026-06-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_hotelbooking_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.room'),
        ),
    ]
