# Generated by Django 5.2.10 on 2026-07-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0011_remove_hotelbooking_is_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/destinations/')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationMustVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/destination/must_visit/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='must_visit_places', to='reserve.destination')),
            ],
        ),
    ]
