# Generated by Django 5.2.10 on 2026-07-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0020_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.vehicle'),
        ),
    ]
