# Generated by Django 5.2.10 on 2026-07-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0021_hotelbooking_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_packages', to='reserve.package')),
            ],
        ),
    ]
