# Generated by Django 5.2.10 on 2026-07-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0022_toppackages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopPackages',
        ),
    ]
