# Generated by Django 5.2.10 on 2026-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0024_user_hotel_owner_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hotel_owner', 'Hotel Owner'), ('customer', 'Customer')], default='customer', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='owner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
